### ISSUE TITLE
Where do I get the clientId and clientSecret, can I generate them myself?

### ISSUE THREAD

**Issue by liuzhiguo630** [VaalaCat/raychat#1]
I've noticed that clientId and clientSecret are required for login, and through a packet capture I can see that they only appear when the raycast client login. I'm worried that reusing them might have bad effects.

**Comment by VaalaCat** [comment]
For your question, you cannot generate those parameters by your self,at least I'm not able to figuring out how it works.

**But!** During my testing, I installed Raycast on multiple Macs and discovered that the client ID and client secret remained the same. I’m curious if these parameters are hardcoded in the Raycast program.

I think it's safe to reuse it.

Here is the MD5 hash of the ID and secret. Please compare it with yours to see if they match.

```
CLIENT_ID 53b8c231096e058eee19d0887a7dbcea

CLIENT_SECRET 00c9272c85ee2c60caa0495ff35dc1c2
```

**Comment by liuzhiguo630** [comment]
It does match your MD5 :) 
I even uninstalled and reinstalled it all sorts of ways, only to find that it hadn't changed, and thought it was calculated from some device information. I was overthinking it.
