### ISSUE TITLE
Gpt4 doesn't seem to be available through the raychat project.

### ISSUE THREAD

**Issue by kuangxiaoye** [VaalaCat/raychat#2]
After the official update of version 1.57.1, it seems that gpt4 has been changed. I can only get the result of gpt3.5 through the raychat project request.The power of calculation has dropped significantly.

After my updated version, the computing power has improved significantly, but the gpt4 request made in the form of raychat token still returns the result of gpt3.5 numeric power.

<img width="1000" alt="image" src="https://github.com/VaalaCat/raychat/assets/43713316/060c9846-3a07-4014-b8f4-7e9b75c7e755">
<img width="1000" alt="image" src="https://github.com/VaalaCat/raychat/assets/43713316/6a34e647-f40a-4b68-b507-20cb0c276b3a">

**Comment by kuangxiaoye** [comment]
I found an extra X-Raycast-Signature parameter in header

**Comment by VaalaCat** [comment]
1.56 Raycast can still get GPT4 working? If so, I Assume that Raycast will block the request to GPT4 without X-Raycast-Signature In the future.

**Comment by kuangxiaoye** [comment]
> 1.56 Raycast can still get GPT4 working? If so, I Assume that Raycast will block the request to GPT4 without X-Raycast-Signature In the future.

No, after I found this problem, I tested it on both versions with my macbookpro and macmini, and the result was that the X-Raycast-Signature parameter completely redirected the model=4.0 to model=3.5.

**Comment by VaalaCat** [comment]
Does this mean that when the X-Raycast-Signature in the request is valid, the Raycast backend will replace the parameter with model=3.5? Or is it that as long as the X-Raycast-Signature header is included, it will be replaced?

**Comment by kuangxiaoye** [comment]
X-Raycast-Signature is a dynamic value. It is observed that the X-Raycast-Signature should be checked at the backend. Set model to gpt-4 if correct, and set model to gpt-3.5 if wrong.

I don't understand why the authorities are doing this.After my exploration, I couldn't find a solution, because unlike the web side, I was relatively new to macos, so I had to ask you for feedback.

**Comment by VaalaCat** [comment]
Currently I can use Raychat to invoke GPT-4 Model. Maybe only account be logged in at  the updated version have this limitation? In short, whenever I encounter this issue, I will delve into the internals of the Raycast Client binary to find out solution!

**Comment by kuangxiaoye** [comment]
Thank you for reminding me. Let me study it.

Vaala Cat ***@***.***> 于2023年8月11日周五 23:05写道：
